[[9392128, "Traceback (most recent call last):\r\n  File \"C:\\Users\\Admin\\Desktop\\YandexLyceum\\Test system\\test-system\\program_testing\\source_solution\\thread_3\\solution.py\", line 1, in <module>\r\n    while true:\r\nNameError: name 'true' is not defined", null, 0.059999942779541016]]