[[2420736, "python3: can't open file '/root/test-system/program_testing/source_solution/thread_3/solution.py': [Errno 2] No such file or directory", null, 0.11896729469299316]]